### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ssoonmi** [randallmlough/invoiced#3]
### Backend Routes
- [x] make sure to put a description saying what each route should be used for
- [x] For members routes, you should have them in nested routes since members is a joins table and you should not be storing the id of the members in your frontend
    - e.g. /api/biz/:biz_id/users/:user_id/members
- [ ] Don't need a PUT/PATCH route for members (either creating a membership or deleting it)

### Frontend Routes
- [x] Please do your frontend routes

**Comment by randallmlough** [comment]
> For members routes, you should have them in nested routes since members is a joins table and **you should not be storing the id of the members in your frontend**
I'm not sure I'm following here. How would we reference a user/member in redux / react without knowing what their id is?

> - [ ] Don't need a PUT/PATCH route for members (either creating a membership or deleting it)
The edit action would be to edit their permissions
